" Sin compatibiladad con Vi
set nocompatible

" Usar <Space> como comando
nmap <Space> :

" En caso de tener problemas como funciona delete y backspace
set backspace=indent,eol,start

" Encoding utilizado dentro de VIM
set encoding=utf-8

" Espacios como tab
set tabstop=2 shiftwidth=2 expandtab

" Identacion automatica 
filetype plugin indent on

" Show line numbers 
set nu

" Habilita color de sintaxis
syntax on

" Display all matching files when tab complete
set wildmenu 

" Set title on
set title

" Set colors for dark backgrounds
set background=dark

" Always show status
set laststatus=2

" Ignore case for search
set ignorecase

" Smart case for search
set smartcase

" Highlight search while typing
set incsearch

" Highlight search
set hlsearch

" yank and paste selection without prepend "* 
set clipboard=unnamed

" use mouse for all modes
set mouse=a

" Set cursor line highlight
set cursorline

" Foldmethod
" set foldmethod=syntax

" Copy Visual Selected and Search
vnoremap // y/<C-R>"<CR>

" Auto Reload .vimrc 
autocmd! bufwritepost .vimrc source %

" Search down into subfolders
" Provides tab-completion for all file-related tasks
set path+=**

" Type MakeTags and create 'tags' file (need ctags to be installed)
command! MakeTags !ctags -R .

" Tweaks file browsing 
let g:netrw_banner=0        " disables banner
let g:netrw_liststyle=3     " tree view

" Statusline
set statusline=%f\ %y%=%{fugitive#statusline()}\ \%l/%L

" Javascript
let g:javascript_plugin_jsdoc = 1
let g:javascript_plugin_ngdoc = 1

" NERDTree
silent! nmap <F4> :NERDTreeToggle<CR>
silent! map <F3> :NERDTreeFind<CR>
let g:NERDTreeMapActivateNode="<F3>"
"let g:NERDTreeMapPreview="<F4>"

" CtrlP
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_root_markers = ['pom.xml', '.p4ignore']
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
let g:ctrlp_user_command = 'find %s -type f' 

" Pathogen
execute pathogen#infect()
