# Environment variables
#export TERM=xterm-256color
export CLICOLOR=1
export LSCOLORS='gxfxcxdxbxegedabagacad'

# Tmux as default

# Bash configuration files
test -f ~/.bash_prompt && source ~/.bash_prompt
test -f ~/.bash_aliases && source ~/.bash_aliases
test -f ~/.bash_extras && source ~/.bash_extras
test -f ~/.profile && source ~/.profile

# rvm - ruby version manager

# Geckodriver - Firefox Web Driver
export PATH=$PATH:/opt/geckodriver

# Go lang
export GOPATH=/Users/miguel/Work/lab/go

# nvm - node version manager
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

# MongoDB
export MONGO_PATH="/usr/local/mongodb"
export ANDROID_SDK="/Users/miguel/Library/Android/sdk"
export PATH="$PATH:$MONGO_PATH/bin:$ANDROID_SDK/tools:$ANDROID_SDK/tools/bin"

# Java
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home"

# jenv
eval "$(jenv init -)"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
