# Environment variables
#export TERM=xterm-256color
export CLICOLOR=1
export LSCOLORS='gxfxcxdxbxegedabagacad'

# Bash configuration files
test -f ~/.bash_prompt && source ~/.bash_prompt
test -f ~/.bash_aliases && source ~/.bash_aliases
test -f ~/.bash_extras && source ~/.bash_extras
test -f ~/.profile && source ~/.profile

# rvm - ruby version manager
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Geckodriver - Firefox Web Driver
export PATH=$PATH:/opt/geckodriver

# Go Language
export GOPATH=/Users/miguel/Work/lab/go/hello

# nvm - node version manager
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"
