# ls
alias ll='ls -ltrh'
alias l='ls -tr'
alias ld='ls -ltrd */'
alias la='ls -a'

# grep
alias g='grep -i --color' 

# tmux
alias tmls='tmux list-sessions'
alias tmat='tmux attach -t'
alias vim='/usr/local/bin/vim'
alias mvim='/usr/local/bin/mvim'
alias jmeter='/Users/miguel/.bzt/jmeter-taurus/3.3/bin/jmeter'

alias L=' | less'

# apps
alias markoff='open -a Markoff'
alias sublime='open -a "Sublime Text"'
alias snes='open -a /Applications/Snes9x.app'
alias nes='open -a /Applications/Nestopia.app'
alias vscode='open -a /Applications/Visual\ Studio\ Code.app'
alias code='open -a /Applications/Code\ -\ OSS.app'

# cucumber
alias be='bundle exec'
alias ccmb='bundle exec cucumber features/'

# directories
alias t-wom='cd /Users/miguel/Work/Tinet/qa/wom/transformacion-loadtests'
alias gomacal='cd /Users/miguel/Work/Tinet/qa/macal'
alias gols='cd /Users/miguel/Work/DevEx/lseg'
